### ISSUE TITLE
Chrome exits upon entering VR mode in HTC Vive.

### ISSUE THREAD

**Issue by swomack** [toji/chrome-webvr-issues#125]
It works fine with Oculus. But when i use Vive, chrome exits when i enter to VR mode.

Chromium Revision: 56.0.2902.0

Here is the log message from Vive log - 

> Wed Jan 04 2017 13:41:14.573 - vrclient startup with PID=12108, type=VRApplication_Scene, config=C:\Program Files (x86)\Steam\config
> Wed Jan 04 2017 13:41:14.574 - [DriverManager] Create new Resource Driver Manager
> Wed Jan 04 2017 13:41:14.575 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
> Wed Jan 04 2017 13:41:14.575 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
> Wed Jan 04 2017 13:41:14.575 - [Settings] Load Default Json Settings from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
> Wed Jan 04 2017 13:41:14.576 - [Settings] Load Json Settings from C:\Program Files (x86)\Steam\config\steamvr.vrsettings
> Wed Jan 04 2017 13:41:15.625 - IPCPipe(VR_ServerPipe): Process disconnected.
> Wed Jan 04 2017 13:41:15.625 - Invalid response to connect message. Connect failed

**Comment by sjpt** [comment]
I have seen a crash on startup on very rare occasions, but for me that version of ChromeVR and Vive work fine together.  I suggest you try experimenting launching two different ways to see if either helps.
1) Do NOT have SteamVR running in advance and let Chrome VR start it as needed.
2) DO have SteamVR running in advance and let Chrome VR use that.

No strong reason to think it will help, but under these situations some experimentation is often the best way forward, especially if the issue is not easily reproduced elsewhere.

It could be there is something about having both VIVE and Oculus runtimes installed together.  Might be worth trying temporarily to disable the Oculus runtime and see if that helps.

**Comment by swomack** [comment]
@sjpt I have tried both of the ways you have mentioned. The result is same. 

I will try disabling Oculus runtime and confirm you if that works.

One more thing, it was working yesterday. In the meantime i updated Stream. One more thing i want to mention, firefox nightly works just fine.

**Comment by paperkettle** [comment]
+1 same issue

**Comment by swomack** [comment]
@paperkettle I uninstalled steam and steamVR. Then installed them again. It seems my problem is solved after that.

**Comment by swomack** [comment]
This problem is back again. Probably related to steamVR update.

**Comment by toji** [comment]
I believe that this is fixed with the most recent build at https://webvr.info/get-chrome

**Comment by oquigley** [comment]
Still getting a fairly immediate crash when entering webVR with your current build and current version of steam.

**Comment by inbalshirina** [comment]
same problem also with the recent builf
