### ISSUE TITLE
`requestPresent` resets pose w/ Oculus Rift

### ISSUE THREAD

**Issue by brianchirls** [toji/chrome-webvr-issues#79]
We need to be able to request presentation without resetting the pose, especially if we want to change the layer parameters for something like adaptive rendering. I don't believe the spec, as it stands, makes any mention of presentation state affecting the pose.

Thanks

**Comment by toji** [comment]
Fixed in the latest build! Thanks for the report!

**Comment by brianchirls** [comment]
I appreciate the quick patch, but I'm not seeing a fix. Pose still resets when I call `requestPresent`, whether or not I'm already presenting.

**Comment by toji** [comment]
Do you have a URL that you can share that demonstrates the issue?

**Comment by brianchirls** [comment]
Sure. This one:
https://toji.github.io/webvr-samples/04-simple-mirroring.html

Can you confirm I'm using the correct build? 53.0.2785.0

**Comment by toji** [comment]
I think I found the problem. One of those "This should be a safe change that I don't need to re-test because it would be a pain to crawl around to the back of the computer to swap headsets again so I'm just going to assume it's still working." bugs. :package: 

Should have a new build out soon with the ACTUAL fix.

**Comment by toji** [comment]
Oh, and I should mention that even with this fix it won't fix the orientation reset the first time you present. That's sadly necessary at the moment to ensure that the image shows in the headset correctly, and will be a bigger fix. (I have plans for it, but may take a while.)

**Comment by brianchirls** [comment]
HA! Surely there's an acronym for that. Problem Exists Between...umm...

**Comment by stuartpb** [comment]
Sounds like a good reason to get some extension cables...

**Comment by toji** [comment]
I actually had them both plugged in for a while. (SteamVR kinda doesn't like that.) Unfortunately there was a bug where the Vive stopped working with DisplayPort for a while, so I was forced back to one headset at a time.

**Comment by toji** [comment]
Should actually truly for-reals-now be fixed in the latest build (July 6th). Sorry!

**Comment by brianchirls** [comment]
I hate to keep coming back to this, but there's still a problem. In today's build, `requestPresent` no longer resets the view, except on the initial call. But now it is not correctly rendering the adjusted viewport.

To see what I mean, please try this example in both the July 6 build and the July 1 build: http://output.jsbin.com/fohuqen

**Comment by toji** [comment]
By all means, keep harping on it as long as it's not fixed! I'll give your demo a try and make sure the next build handles it correctly.

**Comment by toji** [comment]
Got it figured out, posted yet another fixed build. For kicks I updated your demo to make sure that an even more aggressive version works: http://output.jsbin.com/xizujosige That one scales the resolution up and down on a sine wave every 100ms. Still tracks smoothly on my machine!

**Comment by brianchirls** [comment]
Awesome! I'll try it tomorrow morning when I'm back in the office.

How well does it work on the Vive?

**Comment by brianchirls** [comment]
This is working great now! Good job.

There is, however, a slight weird thing, and I'm not sure what's causing it. Have a look at your aggressive version, if you can, with the lenses out. I don't know if you can do that with the CV1, but I tried it with the DK2. The rounded edge of the distorted view moves in and out, I think at the high end of your sine wave. With the lenses in, it causes some strange optical reflection on the far right edge of my peripheral vision. Are you seeing this?
